api_platform:
    title: Congress API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        # These don't really work :-(
        item_operations:
            get: ~
        collection_operations:
            get: ~
