ux_icons:
  aliases:
    Wine: lucide:wine
    Marvel: openmoji:superhero
    Car: mdi:car
    layout-grid: tabler:layout-grid
  default_icon_attributes:
    width: 16px
    height: 16px
    fill: currentColor
  iconify:
    enabled: true
    on_demand: false
  ignore_not_found: false
